name: workers_hub
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Fixed SDK constraint

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  provider: ^6.0.5
  intl: ^0.19.0
  razorpay_flutter: ^1.3.6
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  qr_flutter: ^4.1.0
  fluttertoast: ^8.2.4
  cached_network_image: ^3.4.1
  firebase_storage: ^11.5.6
  permission_handler: ^11.1.0
  url_launcher: ^6.0.20
  lottie: ^2.6.0
  pdf: ^3.10.4
  printing: ^5.12.2
  share_plus: ^7.2.0

  flutter_spinkit: ^5.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

# Flutter Launcher Icons configuration (OUTSIDE of dev_dependencies)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"  # Using JPG file

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg  # Must match the image_path above
    - assets/animations/success.json